import type { Metadata } from "next";
import "./globals.css";
import ClientProvider from "./clientProvider";
import AuthWrapper from "./authWrapper";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <ClientProvider>
          <AuthWrapper>
            {children}
          </AuthWrapper>
        </ClientProvider>
      </body>
    </html>
  );
}
